package com.synapse.lantransfer.util

import android.content.Context
import android.net.ConnectivityManager
import android.net.wifi.WifiManager
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log
import java.net.Inet4Address
import java.net.NetworkInterface
import java.util.Collections

/**
 * Manages programmatically creating a local Wi-Fi Hotspot (LocalOnlyHotspot)
 * on Android 8.0+ devices.
 *
 * The hotspot SSID and password are system-generated by LocalOnlyHotspot.
 * We report fixed display names ("Synapse" / "qwertyui") alongside the actual
 * credentials so the UI can show them consistently.
 *
 * This manager also exposes tethering-detection helpers so the UI can offer
 * a "share over existing hotspot" flow when the user already has Mobile
 * Hotspot (Wi-Fi tethering) running.
 */
class HotspotManager(private val context: Context) {

    companion object {
        private const val TAG = "HotspotManager"

        /**
         * Resolves the device's local IP address on the active Wi-Fi or Hotspot interface.
         */
        fun getLocalIpAddress(): String? {
            try {
                val interfaces = Collections.list(NetworkInterface.getNetworkInterfaces())
                // Check Wi-Fi or Hotspot interfaces first
                for (intf in interfaces) {
                    if (intf.name.contains("wlan") || intf.name.contains("p2p") || intf.name.contains("ap")) {
                        val addrs = Collections.list(intf.inetAddresses)
                        for (addr in addrs) {
                            if (!addr.isLoopbackAddress && addr is Inet4Address) {
                                return addr.hostAddress
                            }
                        }
                    }
                }
                // Fallback to any non-loopback IPv4 address
                for (intf in interfaces) {
                    val addrs = Collections.list(intf.inetAddresses)
                    for (addr in addrs) {
                        if (!addr.isLoopbackAddress && addr is Inet4Address) {
                            return addr.hostAddress
                        }
                    }
                }
            } catch (ex: Exception) {
                Log.e(TAG, "Error getting local IP address", ex)
            }
            return null
        }
    }

    private val wifiManager: WifiManager by lazy {
        context.applicationContext.getSystemService(Context.WIFI_SERVICE) as WifiManager
    }

    private var hotspotReservation: WifiManager.LocalOnlyHotspotReservation? = null

    // ── Tethering detection ──────────────────────────────────────────────────

    /**
     * Returns true if the user's personal Mobile Hotspot (Wi-Fi tethering) is
     * currently active.
     *
     * LocalOnlyHotspot cannot coexist with tethering because both compete for the
     * same Wi-Fi radio in AP mode. When this returns true, the app should skip
     * creating a new hotspot and instead host files directly on the existing
     * tethering network.
     */
    fun isTetheringActive(): Boolean {
        return try {
            // ConnectivityManager.getTetheredIfaces() lists all interfaces that are
            // actively tethered (Wi-Fi hotspot, USB, Bluetooth). We look for a wlan
            // or ap* interface to detect Wi-Fi hotspot specifically.
            val cm = context.applicationContext
                .getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
            @Suppress("DEPRECATION")
            val tethered = cm.tetheredIfaces ?: emptyArray()
            tethered.any { it.startsWith("wlan") || it.startsWith("ap") }
        } catch (e: Exception) {
            Log.w(TAG, "Could not check tethering state via ConnectivityManager: ${e.message}")
            // Fallback: use the deprecated (but functional) isWifiApEnabled reflection call
            try {
                @Suppress("DEPRECATION")
                val method = wifiManager.javaClass.getMethod("isWifiApEnabled")
                method.invoke(wifiManager) as? Boolean ?: false
            } catch (ex: Exception) {
                false
            }
        }
    }

    /**
     * Returns the IPv4 address of this device on the active Wi-Fi tethering
     * (Mobile Hotspot) network — i.e. the address connected computers can reach.
     *
     * The approach:
     *  1. Ask ConnectivityManager which interface is tethered.
     *  2. Look up the IPv4 address on that specific interface.
     *  3. Fallback to scanning known hotspot interface names (ap0, wlan1, …).
     *  4. Last resort: return the Android hotspot gateway default "192.168.43.1".
     */
    fun getTetheringIpAddress(): String {
        try {
            // Step 1: find the tethered Wi-Fi interface name
            val cm = context.applicationContext
                .getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
            @Suppress("DEPRECATION")
            val tethered = cm.tetheredIfaces ?: emptyArray()
            val tetherIface = tethered.firstOrNull {
                it.startsWith("wlan") || it.startsWith("ap")
            }

            if (tetherIface != null) {
                // Step 2: resolve its IPv4 address
                val netIface = NetworkInterface.getByName(tetherIface)
                val addrs = Collections.list(netIface?.inetAddresses ?: return@getTetheringIpAddress "192.168.43.1")
                val ip = addrs.filterIsInstance<Inet4Address>()
                    .firstOrNull { !it.isLoopbackAddress }
                    ?.hostAddress
                if (ip != null) return ip
            }
        } catch (e: Exception) {
            Log.w(TAG, "Could not resolve tethering IP via ConnectivityManager: ${e.message}")
        }

        // Step 3: scan well-known AP interface names
        try {
            val knownApNames = listOf("ap0", "wlan1", "swlan0", "swlan1")
            for (name in knownApNames) {
                val netIface = NetworkInterface.getByName(name) ?: continue
                val addrs = Collections.list(netIface.inetAddresses)
                val ip = addrs.filterIsInstance<Inet4Address>()
                    .firstOrNull { !it.isLoopbackAddress }
                    ?.hostAddress
                if (ip != null) return ip
            }
        } catch (e: Exception) {
            Log.w(TAG, "Could not scan AP interfaces: ${e.message}")
        }

        // Step 4: Android's historical default gateway for Mobile Hotspot
        return "192.168.43.1"
    }

    // ── LocalOnlyHotspot ─────────────────────────────────────────────────────

    /**
     * Start a new local-only Wi-Fi Hotspot (for "Hotspot Direct Share" mode).
     *
     * Call [isTetheringActive] before this method. If the user's Mobile Hotspot is
     * already running, skip this call entirely and use [getTetheringIpAddress]
     * instead — the two AP modes cannot coexist on the same Wi-Fi radio.
     */
    fun startHotspot(
        onStarted: (ssid: String, wpa2Key: String) -> Unit,
        onFailed: (error: String) -> Unit
    ) {
        if (hotspotReservation != null) {
            onFailed("Hotspot is already running")
            return
        }

        try {
            if (!wifiManager.isWifiEnabled) {
                @Suppress("DEPRECATION")
                wifiManager.isWifiEnabled = true
            }

            wifiManager.startLocalOnlyHotspot(object : WifiManager.LocalOnlyHotspotCallback() {
                override fun onStarted(reservation: WifiManager.LocalOnlyHotspotReservation) {
                    super.onStarted(reservation)
                    hotspotReservation = reservation

                    // Extract actual SSID and password from the reservation.
                    // On API 33+ use SoftApConfiguration; on older use deprecated WifiConfiguration.
                    var ssid: String? = null
                    var psk: String? = null

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                        val softApConfig = reservation.softApConfiguration
                        ssid = softApConfig?.ssid
                        psk = softApConfig?.passphrase
                    } else {
                        @Suppress("DEPRECATION")
                        val config = reservation.wifiConfiguration
                        ssid = config?.SSID?.removeSurrounding("\"")
                        psk = config?.preSharedKey?.removeSurrounding("\"")
                    }

                    // Report the actual system-generated SSID and password so the connecting
                    // device can connect successfully.
                    onStarted(
                        ssid ?: "Synapse",
                        psk ?: "qwertyui"
                    )
                }

                override fun onFailed(reason: Int) {
                    super.onFailed(reason)
                    val errorMsg = when (reason) {
                        WifiManager.LocalOnlyHotspotCallback.ERROR_NO_CHANNEL ->
                            "No Wi-Fi channel available. Try disabling Bluetooth or other wireless features."
                        WifiManager.LocalOnlyHotspotCallback.ERROR_GENERIC ->
                            "Could not create the Wi-Fi hotspot (generic error). Please try again."
                        WifiManager.LocalOnlyHotspotCallback.ERROR_INCOMPATIBLE_MODE ->
                            "Cannot start Wi-Fi Direct Share: another Wi-Fi feature (e.g. Mobile Hotspot) " +
                            "is already using the Wi-Fi radio. Turn it off in Settings and try again."
                        WifiManager.LocalOnlyHotspotCallback.ERROR_TETHERING_DISALLOWED ->
                            "Wi-Fi hotspot is not allowed by your carrier or device policy."
                        else ->
                            "Hotspot creation failed (reason: $reason)"
                    }
                    onFailed(errorMsg)
                }
            }, Handler(Looper.getMainLooper()))
        } catch (e: SecurityException) {
            onFailed("Location permissions required to create hotspot")
        } catch (e: Exception) {
            onFailed("Error starting hotspot: ${e.message}")
        }
    }

    /**
     * Stop the local hotspot and restore Wi-Fi state.
     */
    fun stopHotspot() {
        try {
            hotspotReservation?.close()
        } catch (e: Exception) {
            Log.e(TAG, "Error closing hotspot reservation", e)
        }
        hotspotReservation = null
    }
}
