package com.synapse.lantransfer.util

import android.content.Context
import android.net.wifi.WifiManager
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log
import java.net.Inet4Address
import java.net.NetworkInterface
import java.util.Collections

/**
 * Manages programmatically creating a local Wi-Fi Hotspot (LocalOnlyHotspot)
 * on Android 8.0+ devices.
 *
 * The hotspot SSID and password are system-generated by LocalOnlyHotspot.
 * We report fixed display names ("Synapse" / "qwertyui") alongside the actual
 * credentials so the UI can show them consistently.
 *
 * This manager also exposes tethering-detection helpers so the UI can offer
 * a "share over existing hotspot" flow when the user already has Mobile
 * Hotspot (Wi-Fi tethering) running.
 */
class HotspotManager(private val context: Context) {

    companion object {
        private const val TAG = "HotspotManager"

        /**
         * Resolves the device's local IP address on the active Wi-Fi or Hotspot interface.
         */
        fun getLocalIpAddress(): String? {
            try {
                val interfaces = Collections.list(NetworkInterface.getNetworkInterfaces())
                // Check Wi-Fi or Hotspot interfaces first
                for (intf in interfaces) {
                    if (intf.name.contains("wlan") || intf.name.contains("p2p") || intf.name.contains("ap")) {
                        val addrs = Collections.list(intf.inetAddresses)
                        for (addr in addrs) {
                            if (!addr.isLoopbackAddress && addr is Inet4Address) {
                                return addr.hostAddress
                            }
                        }
                    }
                }
                // Fallback to any non-loopback IPv4 address
                for (intf in interfaces) {
                    val addrs = Collections.list(intf.inetAddresses)
                    for (addr in addrs) {
                        if (!addr.isLoopbackAddress && addr is Inet4Address) {
                            return addr.hostAddress
                        }
                    }
                }
            } catch (ex: Exception) {
                Log.e(TAG, "Error getting local IP address", ex)
            }
            return null
        }
    }

    private val wifiManager: WifiManager by lazy {
        context.applicationContext.getSystemService(Context.WIFI_SERVICE) as WifiManager
    }

    private var hotspotReservation: WifiManager.LocalOnlyHotspotReservation? = null

    // ── Tethering detection ──────────────────────────────────────────────────

    /**
     * Returns true if the user's personal Mobile Hotspot (Wi-Fi tethering) is
     * currently active.
     *
     * LocalOnlyHotspot cannot coexist with tethering because both compete for the
     * same Wi-Fi radio in AP mode. When this returns true, the app should skip
     * creating a new hotspot and instead host files directly on the existing
     * tethering network.
     */
    /**
     * Returns true if the user's personal Mobile Hotspot (Wi-Fi tethering) is
     * currently active.
     *
     * Uses two permission-free strategies that work across all API levels:
     *  1. WifiManager.isWifiApEnabled() via reflection.
     *  2. Scanning network interfaces for a live AP interface (ap0, wlan1, …).
     *
     * Note: ConnectivityManager.getTetheredIfaces() was intentionally avoided —
     * it requires the TETHER_PRIVILEGED signature permission on Android 10+ and
     * is therefore inaccessible to regular apps.
     */
    fun isTetheringActive(): Boolean {
        // Strategy 1: WifiManager hidden API via reflection (fast, reliable)
        try {
            val method = wifiManager.javaClass.getMethod("isWifiApEnabled")
            val result = method.invoke(wifiManager)
            if (result is Boolean && result) return true
        } catch (e: Exception) {
            Log.w(TAG, "isWifiApEnabled reflection failed: ${e.message}")
        }

        // Strategy 2: Look for a live AP network interface as a fallback
        return hasActiveApInterface()
    }

    /**
     * Returns the IPv4 address of this device on the active Wi-Fi tethering
     * (Mobile Hotspot) network — i.e. the address connected devices can reach.
     *
     * Scans network interfaces for well-known AP names (ap0, wlan1, swlan*, …)
     * and any other UP interface whose name starts with "ap" or "wlan".
     * Falls back to Android's historical hotspot gateway "192.168.43.1".
     */
    fun getTetheringIpAddress(): String {
        try {
            // Priority: well-known AP interface names used by most Android OEMs
            val knownApNames = listOf("ap0", "wlan1", "swlan0", "swlan1", "wlan2")
            for (name in knownApNames) {
                val netIface = NetworkInterface.getByName(name) ?: continue
                if (!netIface.isUp) continue
                val ip = Collections.list(netIface.inetAddresses)
                    .filterIsInstance<Inet4Address>()
                    .firstOrNull { !it.isLoopbackAddress }
                    ?.hostAddress
                if (ip != null) {
                    Log.d(TAG, "Tethering IP resolved on $name: $ip")
                    return ip
                }
            }

            // Broader scan: any UP interface whose name starts with "ap" or "wlan"
            val allInterfaces = Collections.list(NetworkInterface.getNetworkInterfaces())
            for (iface in allInterfaces) {
                if (!iface.isUp) continue
                if (!iface.name.startsWith("ap") && !iface.name.startsWith("wlan")) continue
                val ip = Collections.list(iface.inetAddresses)
                    .filterIsInstance<Inet4Address>()
                    .firstOrNull { !it.isLoopbackAddress }
                    ?.hostAddress
                if (ip != null) {
                    Log.d(TAG, "Tethering IP resolved on ${iface.name}: $ip")
                    return ip
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Error scanning interfaces for tethering IP: ${e.message}")
        }

        // Last resort: Android's historical default gateway for Mobile Hotspot
        Log.w(TAG, "Could not resolve tethering IP, using default 192.168.43.1")
        return "192.168.43.1"
    }

    /**
     * Returns true if any network interface that looks like a Wi-Fi AP
     * (name starting with "ap" or "wlan") is currently UP and has an IPv4 address.
     */
    private fun hasActiveApInterface(): Boolean {
        return try {
            val interfaces = Collections.list(NetworkInterface.getNetworkInterfaces())
            interfaces.any { iface ->
                iface.isUp &&
                (iface.name.startsWith("ap") || iface.name.startsWith("wlan")) &&
                Collections.list(iface.inetAddresses).any { addr ->
                    !addr.isLoopbackAddress && addr is Inet4Address
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "hasActiveApInterface scan failed: ${e.message}")
            false
        }
    }

    // ── LocalOnlyHotspot ─────────────────────────────────────────────────────

    /**
     * Start a new local-only Wi-Fi Hotspot (for "Hotspot Direct Share" mode).
     *
     * Call [isTetheringActive] before this method. If the user's Mobile Hotspot is
     * already running, skip this call entirely and use [getTetheringIpAddress]
     * instead — the two AP modes cannot coexist on the same Wi-Fi radio.
     */
    fun startHotspot(
        onStarted: (ssid: String, wpa2Key: String) -> Unit,
        onFailed: (error: String) -> Unit
    ) {
        if (hotspotReservation != null) {
            onFailed("Hotspot is already running")
            return
        }

        try {
            if (!wifiManager.isWifiEnabled) {
                @Suppress("DEPRECATION")
                wifiManager.isWifiEnabled = true
            }

            wifiManager.startLocalOnlyHotspot(object : WifiManager.LocalOnlyHotspotCallback() {
                override fun onStarted(reservation: WifiManager.LocalOnlyHotspotReservation) {
                    super.onStarted(reservation)
                    hotspotReservation = reservation

                    // Extract actual SSID and password from the reservation.
                    // On API 33+ use SoftApConfiguration; on older use deprecated WifiConfiguration.
                    var ssid: String? = null
                    var psk: String? = null

                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                        val softApConfig = reservation.softApConfiguration
                        ssid = softApConfig?.ssid
                        psk = softApConfig?.passphrase
                    } else {
                        @Suppress("DEPRECATION")
                        val config = reservation.wifiConfiguration
                        ssid = config?.SSID?.removeSurrounding("\"")
                        psk = config?.preSharedKey?.removeSurrounding("\"")
                    }

                    // Report the actual system-generated SSID and password so the connecting
                    // device can connect successfully.
                    onStarted(
                        ssid ?: "Synapse",
                        psk ?: "qwertyui"
                    )
                }

                override fun onFailed(reason: Int) {
                    super.onFailed(reason)
                    val errorMsg = when (reason) {
                        WifiManager.LocalOnlyHotspotCallback.ERROR_NO_CHANNEL ->
                            "No Wi-Fi channel available. Try disabling Bluetooth or other wireless features."
                        WifiManager.LocalOnlyHotspotCallback.ERROR_GENERIC ->
                            "Could not create the Wi-Fi hotspot (generic error). Please try again."
                        WifiManager.LocalOnlyHotspotCallback.ERROR_INCOMPATIBLE_MODE ->
                            "Cannot start Wi-Fi Direct Share: another Wi-Fi feature (e.g. Mobile Hotspot) " +
                            "is already using the Wi-Fi radio. Turn it off in Settings and try again."
                        WifiManager.LocalOnlyHotspotCallback.ERROR_TETHERING_DISALLOWED ->
                            "Wi-Fi hotspot is not allowed by your carrier or device policy."
                        else ->
                            "Hotspot creation failed (reason: $reason)"
                    }
                    onFailed(errorMsg)
                }
            }, Handler(Looper.getMainLooper()))
        } catch (e: SecurityException) {
            onFailed("Location permissions required to create hotspot")
        } catch (e: Exception) {
            onFailed("Error starting hotspot: ${e.message}")
        }
    }

    /**
     * Stop the local hotspot and restore Wi-Fi state.
     */
    fun stopHotspot() {
        try {
            hotspotReservation?.close()
        } catch (e: Exception) {
            Log.e(TAG, "Error closing hotspot reservation", e)
        }
        hotspotReservation = null
    }
}
